### ISSUE TITLE
File Conversion Sorry, we can into a problem

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/officeonline#236]
**Describe the bug**
Open a doc file and convert it into docx. once you open the file and conver it get an error. Please see below screen record. 

https://user-images.githubusercontent.com/59488153/144658599-9907b860-6363-4c0b-817a-8f1b7dc3b68f.mp4

If dev need a test server to connect ill be more then happy to give you Online office server url. 

## Server details
**Operating system**:
Ubuntu 20.04
**Web server:**
Apache
**Database:**
MariaDB 10.5.13
**PHP version:**
8.0.13
**Nextcloud version:**
23.0.0
**Version of the officeonline app**
1.1.1
**Version of Office Online server**
2019

**Comment by juliushaertl** [comment]
Do you have any errors logged on either the office online or Nextcloud side?

**Comment by andyxheli** [comment]
Nope nothing on the server side I can't try again and see

**Comment by andyxheli** [comment]
@juliushaertl  So what happens is that the file is a .doc and to edited file it needs to be .docx so when I click on convert is dose convert the file but when it converts it it create a file name New File and dose not keep the same file name so i think it erroring out because if you leave the page refresh the screen shows the new file but not with the same name its labeled New File.docx and the original file was named Doc1.doc hope this helps a little

**Comment by olivier-nextcloud** [comment]
Hi,
Same problem with my setup. 
No logs at all neither on Nextcloud side nor Office side.
Help would be very appreciated.

Server details :
Operating system:
Debian 10
Web server:
Nginx 1.14.2
Database:
MariaDB 10.3.31
PHP version:
7.4.27
Nextcloud version:
22.2.3
Version of the officeonline app
1.1.2
Version of Office Online server
2019
