### ISSUE TITLE
Office 365 integration for large institutions

### ISSUE THREAD

**Issue by andbag** [nextcloud/officeonline#512]
With reference to https://github.com/nextcloud/officeonline/issues/369

Given Nextcloud's fair use policy, enterprise customers who manage more than 500 users are already required to purchase licenses for the notification service. With this in mind, it would make sense to consider developing a solution similar to Owncloud's approach for integration with Office 365 that is specifically tailored to this customer segment and offered as a paid feature. Large public institutions in particular are looking for a compromise between user acceptance and strict data protection standards. There is also an urgent need for an exit strategy for Office 365, especially in the event that the Data Privacy Framework is declared invalid. I am sure that these institutions would be very willing to invest in this solution. Have other major customers already requested this feature?

**Comment by juliushaertl** [comment]
We have discussed this option internally but came to the conclusion that implementing a solution where Nextcloud would act as a service provider and therefore have access to the actual files that get opened is currently not a solution we want to go for.

The push notification service is kind of different there as it is more a core functionality without any other feasible options and the protocol was implemented with encryption of the **[actual push message content by design.](https://nextcloud.com/blog/nextclouds-push-notifications-for-ios-and-android/)**, however we do not see a similar option to be feasible with O365.

If there is business interest in such a feature feel free to contact our sales team to talk about options.
